name: MERN CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Login to DockerHub
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u purvapatel1234 --password-stdin

    # 3️⃣ Build Backend Image
    - name: Build Backend
      run: docker build -t purvapatel1234/backend ./backend

    # 4️⃣ Build Frontend Image
    - name: Build Frontend
      run: docker build -t purvapatel1234/frontend ./frontend

    # 5️⃣ Push Images
    - name: Push Images
      run: |
        docker push purvapatel1234/backend
        docker push purvapatel1234/frontend

    # 6️⃣ Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Pull images
          sudo docker pull purvapatel1234/backend
          sudo docker pull purvapatel1234/frontend

          # Create network
          sudo docker network create mern-net || true

          # Stop old containers
          sudo docker stop mongo || true
          sudo docker rm mongo || true

          sudo docker stop backend || true
          sudo docker rm backend || true

          sudo docker stop frontend || true
          sudo docker rm frontend || true

          # Run MongoDB
          sudo docker run -d \
            --name mongo \
            --network mern-net \
            -p 27017:27017 \
            mongo

          # Run Backend
          sudo docker run -d \
            --name backend \
            --network mern-net \
            -p 5000:5000 \
            purvapatel1234/backend

          # Run Frontend
          sudo docker run -d \
            --name frontend \
            --network mern-net \
            -p 3000:3000 \
            purvapatel1234/frontend
